---

- name: Install Elasticsearch extra packages
  become: yes
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ elasticsearch.packages }}"
  notify: restart elasticsearch

- name: Install 1.x Family
  include: install/1.x.yml
  when: elasticsearch.family == '1.x'

- name: Install 2.x Family
  include: install/2.x.yml
  when: elasticsearch.family == '2.x'

- name: Install 5.x+ Family
  include: install/5.x.plus.yml
  when: elasticsearch.family != '1.x' and elasticsearch.family != '2.x'

- name: Ensure some required directories
  become: yes
  file:
    group: "{{ elasticsearch.group }}"
    owner: "{{ elasticsearch.user }}"
    path: "/home/{{ elasticsearch.user }}/{{ item }}"
    state: directory
  with_items:
    - bin

- name: Ensure Elasticsearch service is enabled
  become: yes
  service:
    name: elasticsearch
    enabled: yes
